name: language-modeling-env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - torchtext=0.17.2
  - torchdata=0.7.1
  - pip
  - pip:
      - torchmetrics==1.3.1
      - tqdm==4.67.1
      - numpy==1.26.4
      - portalocker>=2.0.0